export const sourceAllergen = [
    { "id": 1, "name": "Lait", "id_categorie": 1 },
    { "id": 2, "name": "Lactose", "id_categorie": 1 },
    { "id": 3, "name": "Fromage de chèvre", "id_categorie": 1 },
    { "id": 4, "name": "Crème", "id_categorie": 1 },
    { "id": 5, "name": "Amandes", "id_categorie": 2 },
    { "id": 6, "name": "Noisettes", "id_categorie": 2 },
    { "id": 7, "name": "Noix", "id_categorie": 2 },
    { "id": 8, "name": "Pistaches", "id_categorie": 2 },
    { "id": 9, "name": "Gluten", "id_categorie": 3 },
    { "id": 10, "name": "Blé", "id_categorie": 3 },
    { "id": 11, "name": "Orge", "id_categorie": 3 },
    { "id": 12, "name": "Seigle", "id_categorie": 3 },
    { "id": 13, "name": "Crabe", "id_categorie": 4 },
    { "id": 14, "name": "Crevettes", "id_categorie": 4 },
    { "id": 15, "name": "Thon", "id_categorie": 4 },
    { "id": 16, "name": "Saumon", "id_categorie": 4 },
    { "id": 17, "name": "Oeufs", "id_categorie": 5 },
    { "id": 18, "name": "Protéines de blanc d'œuf", "id_categorie": 5 },
    { "id": 19, "name": "Arachides", "id_categorie": 6 },
    { "id": 20, "name": "Lentilles", "id_categorie": 6 },
    { "id": 21, "name": "Pois chiches", "id_categorie": 6 },
    { "id": 22, "name": "Haricots rouges", "id_categorie": 6 },
    { "id": 23, "name": "Sulfites", "id_categorie": 7 },
    { "id": 24, "name": "Nitrites", "id_categorie": 7 },
    { "id": 25, "name": "Tartrazine", "id_categorie": 7 },
    { "id": 26, "name": "Glutamate monosodique", "id_categorie": 7 },
    { "id": 27, "name": "Boeuf", "id_categorie": 8 },
    { "id": 28, "name": "Poulet", "id_categorie": 8 },
    { "id": 29, "name": "Agneau", "id_categorie": 8 },
    { "id": 30, "name": "Porc", "id_categorie": 8 },
    { "id": 31, "name": "Soja", "id_categorie": 9 },
    { "id": 32, "name": "Tofu", "id_categorie": 9 },
    { "id": 33, "name": "Lécithine de soja", "id_categorie": 9 },
    { "id": 34, "name": "Edamame", "id_categorie": 9 },
    { "id": 35, "name": "Maïs", "id_categorie": 10 },
    { "id": 36, "name": "Riz", "id_categorie": 10 },
    { "id": 37, "name": "Avoine", "id_categorie": 10 },
    { "id": 38, "name": "Sarrasin", "id_categorie": 10 }
]