export const sourceUser = [
    {
        "id": 1,
        "email": "john.doe@example.com",
        "password": "password123",
        "age": 30,
        "firstname": "John",
        "lastname": "Doe",
        "gender": "Male",
    },
    {
        "id": 2,
        "email": "jane.smith@example.com",
        "password": "password456",
        "age": 25,
        "firstname": "Jane",
        "lastname": "Smith",
        "gender": "Female",
    },
    {
        "id": 3,
        "email": "alice.johnson@example.com",
        "password": "alicepass789",
        "age": 22,
        "firstname": "Alice",
        "lastname": "Johnson",
        "gender": "Female",
    },
    {
        "id": 4,
        "email": "michael.brown@example.com",
        "password": "michaelpass321",
        "age": 35,
        "firstname": "Michael",
        "lastname": "Brown",
        "gender": "Male",
    },
    {
        "id": 5,
        "email": "linda.white@example.com",
        "password": "lindapass654",
        "age": 28,
        "firstname": "Linda",
        "lastname": "White",
        "gender": "Female",
    },
    {
        "id": 6,
        "email": "robert.jones@example.com",
        "password": "robertpass987",
        "age": 40,
        "firstname": "Robert",
        "lastname": "Jones",
        "gender": "Male",
    },
    {
        "id": 7,
        "email": "susan.miller@example.com",
        "password": "susanpass123",
        "age": 32,
        "firstname": "Susan",
        "lastname": "Miller",
        "gender": "Female",
    },
    {
        "id": 8,
        "email": "david.moore@example.com",
        "password": "davidpass456",
        "age": 27,
        "firstname": "David",
        "lastname": "Moore",
        "gender": "Male",
    },
    {
        "id": 9,
        "email": "emma.taylor@example.com",
        "password": "emmapass789",
        "age": 24,
        "firstname": "Emma",
        "lastname": "Taylor",
        "gender": "Female",
    },
    {
        "id": 10,
        "email": "daniel.anderson@example.com",
        "password": "danielpass321",
        "age": 31,
        "firstname": "Daniel",
        "lastname": "Anderson",
        "gender": "Male",
    }
]