export const sourceUser = [
    {
        "id": 1,
        "email": "john.doe@example.com",
        "password": "password123",
        "age": 30,
        "name": "John Doe",
        "gender": "Male",
    },
    {
        "id": 2,
        "email": "jane.smith@example.com",
        "password": "password456",
        "age": 25,
        "name": "Jane Smith",
        "gender": "Female",
    },
    {
        "id": 3,
        "email": "alice.johnson@example.com",
        "password": "alicepass789",
        "age": 22,
        "name": "Alice Johnson",
        "gender": "Female",
    },
    {
        "id": 4,
        "email": "michael.brown@example.com",
        "password": "michaelpass321",
        "age": 35,
        "name": "Michael Brown",
        "gender": "Male",
    },
    {
        "id": 5,
        "email": "linda.white@example.com",
        "password": "lindapass654",
        "age": 28,
        "name": "Linda White",
        "gender": "Female",
    },
    {
        "id": 6,
        "email": "robert.jones@example.com",
        "password": "robertpass987",
        "age": 40,
        "name": "Robert Jones",
        "gender": "Male",
    },
    {
        "id": 7,
        "email": "susan.miller@example.com",
        "password": "susanpass123",
        "age": 32,
        "name": "Susan Miller",
        "gender": "Female",
    },
    {
        "id": 8,
        "email": "david.moore@example.com",
        "password": "davidpass456",
        "age": 27,
        "name": "David Moore",
        "gender": "Male",
    },
    {
        "id": 9,
        "email": "emma.taylor@example.com",
        "password": "emmapass789",
        "age": 24,
        "name": "Emma Taylor",
        "gender": "Female",
    },
    {
        "id": 10,
        "email": "daniel.anderson@example.com",
        "password": "danielpass321",
        "age": 31,
        "name": "Daniel Anderson",
        "gender": "Male",
    }
]